### ISSUE TITLE
listing loadbalancers doesn't work.

### ISSUE THREAD

**Issue by martindanko** [wallix/awless#103]
Hi,

No matter what account I use, all of which have ELB's, whenever I issue 
`awless list loadbalancers`  
I always get the following

> No results found.

Other than that, **awless** is absolutely awesome. Good job. :smile:

**Comment by simcap** [comment]
@martindanko Thanks for reporting.

First note that `awless` only consider **ELB version 2** (ELBV2). But if you think your load balancers are V2, then let's try the following. 

Get a bit of a debug context by listing again with the extra verbose flag:

`awless ls loadbalancers -e` 

Make sure you are happy with the _aws region and profile_ displayed (i.e. used to fetch data)

Then you can also do a sync manually to check out what is fetched:

`awless sync -e`

Can you then dump the results of those commands in this issue (anonymizing any data you do not want to show).

**Comment by martindanko** [comment]
@simcap - That may explain it, I don't believe I have any v2 ELB's. Is there a reason *awless* only supports v2 ones?

Thanks for your quick reply.

**Comment by simcap** [comment]
No reason in particular for not supporting classic ELB yet apart from prioritizing on other service integration and features so far

But it is on our list as there are a lot of classic AWS ELB out there.

Issue #71 is already opened for that and will track the progress. Feel free to implement it with a pull request.

I will close this issue then.
