### ISSUE TITLE
Support for Credential files using Cross Account and MFA's

### ISSUE THREAD

**Issue by jrudge-kcom** [wallix/awless#104]
Hi,

I access a lot of accounts and have my credentials files set up to assume roles and use an MFA device, however you don't appear to support MFA.

Assume Role MFA token code: Error: Your AWS credentials seem undefined! AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY need to be exported in your CLI environment
Installation documentation is at https://github.com/wallix/awless/wiki/Installation

My credentials file looks like this:

[default]
aws_access_key_id = xxxxxxxxxxxxxxxxxxxxx
aws_secret_access_key = xxxxxxxxxxxxxxxxxxxxxxxxxx
[testaccount]
role_arn = arn:aws:iam::12345678910:role/xxxxxxx
source_profile = default
mfa_serial = arn:aws:iam::12345678910:mfa/jrudge

**Comment by simcap** [comment]
@jrudge-kcom we support MFA (see issue #60 ) and we use it ourselves. 

If I am not mistaken the profile (here with MFA) should be picked correctly if it is defined in the AWS config file (i.e. _~/.aws/config_). Not sure if this works when it is in the shared credentials file (i.e. _~/.aws/credentials_). 

(Note that when defining extra profiles in the AWS config file you create a new section by prefixing with _profile_: ex: [profile my-mfa-profile])

**Comment by fxaguessy** [comment]
@jrudge-kcom did you succeed to connect to AWS using MFA ? 
FYI, for now, there is no caching of STS credentials (cf. #109), so the CLI will ask you a MFA token for each command.

**Comment by captind** [comment]
@fxaguessy I haven't had another chance to look yet. I am aware it won't cache the MFA. I am fine with that it just doesn't seem to recognise the fact I have loaded a profile. It works fine for all the other tools I use (including the AWS CLI).

**Comment by fxaguessy** [comment]
OK, did you try with the `-v` verbose flag, which displays the profile used to launch the session (given with, for example `-p my-profile-name`) ?
