### ISSUE TITLE
brew install fails to work with macOS Sierra

### ISSUE THREAD

**Issue by wiicode** [wallix/awless#105]
Ran into "This formula either does not compile or function as expected on OS X
versions newer than El Capitan due to an upstream incompatibility" when installing on macOS Sierra.

**Comment by simcap** [comment]
@wiicode Thanks for reporting. We will look into that. In the meantime you can install `awless` on OSX easily with:

`curl https://raw.githubusercontent.com/wallix/awless/master/getawless.sh | bash`

**Comment by wiicode** [comment]
Yupp @simcap, aware I have the other options.  Brew was the first one I tried.

**Comment by fxaguessy** [comment]
This is a strange behavior as the brew formula was built on macOS Sierra and I successfully tested on several mac with macOS Sierra. 

Could you first run `brew update; brew tap wallix/awless; brew install awless -v` and put here the output. 

As this might be a `go` dependency problem, could you also try a `brew upgrade go`

**Comment by fxaguessy** [comment]
@wiicode, do you still have this issue after running `brew upgrade go` ?

**Comment by wiicode** [comment]
Might actually have an issue with brew.  I'll reinstall and revisit.

**Comment by wiicode** [comment]
Looks like **brew** got skunked.  Old install that sustained numerous upgrades of OSX and now macOS.  Looks like it broke some bits.  Removed the whole thing, reinstalled it, and **awless** worked well. Sorry about that, should have noticed it sooner.
