### ISSUE TITLE
Edits to "Getting Started" wiki page

### ISSUE THREAD

**Issue by peterkaminski** [wallix/awless#108]
Hi, here are some suggested edits to the Getting Started page of the wiki.  I've attached a patch against revision 64e48fd, since I don't think I can submit a pull request against the github wiki pages.

The changes correct a few typos / spelling errors, and also include some changes to make the language just a little more idiomatic.  (It is already quite good.)

[0001-Typo-fixes-and-fixes-to-make-language-more-idiomatic.patch.txt](https://github.com/wallix/awless/files/1058875/0001-Typo-fixes-and-fixes-to-make-language-more-idiomatic.patch.txt)

**Comment by simcap** [comment]
@peterkaminski Thanks for that! I have just applied your patch and pushed it to the wiki.

Our wiki should be editable by anyone (I have to double check that actually) so next time feel free to edit it directly.

Closing issue.
