### ISSUE TITLE
Support caching STS credentials

### ISSUE THREAD

**Issue by jmhale** [wallix/awless#109]
awless doesn't cache the temporary STS credentials returned by AWS, so when MFA is enforced on an account, the MFA token must be entered for every command.

This is contrary to how `awscli` operates, which only re-prompts for MFA when the STS credentials expire.

This was referenced and responded to in #60, but I didn't see an actual issue opened for it to track.

**Comment by fxaguessy** [comment]
As far as I know, there is currently no way in aws-sdk-go to cache credentials between sessions. I just created an issue on `aws-sdk-go` (https://github.com/aws/aws-sdk-go/issues/1329) to confirm that.
However, we agree, this feature is essential for MFA to be effectively usable.

**Comment by fxaguessy** [comment]
Hello @jmhale and @deinspanjer, I just added in 5a73223, available on `master`, a basic implementation to support STS credentials caching for MFA (for now, credentials are cached for 15 minutes).
Could you test that it works for your use cases ?

**Comment by xp-1000** [comment]
Hi @fxaguessy, I just tested and it works like a charm even with multiple accounts assume roles.
Thank you I will be able to start using this tool

**Comment by deinspanjer** [comment]
How exactly did you install?  I've been using brew, but I get an error trying to instead HEAD:
```
==> Installing awless from wallix/awless
==> Cloning https://github.com/wallix/awless.git
Updating /Users/dre/Library/Caches/Homebrew/awless--git
==> Checking out branch master
==> go run release.go -tag vHEAD-4073113 -brew -arch amd64 -os darwin
Error: No such file or directory - awless
```

**Comment by jmhale** [comment]
@fxaguessy Works great! Thanks!

**Comment by fxaguessy** [comment]
@xp-1000 @jmhale , great to know, thanks for your feedback !

@deinspanjer, `awless` in homebrew can not be installed at a specific commit (I just created an issue at https://github.com/wallix/homebrew-awless/issues/1 to support that). If you want to install the `HEAD` version, you can run `go get -u github.com/wallix/awless` to fetch and build the last version. Otherwise, you just have to wait the release of v0.1.2, which might happen soon.
