### ISSUE TITLE
Include Vpcid in output  and filter upon VpcId

### ISSUE THREAD

**Issue by maishsk** [wallix/awless#113]
For most resources there is an association to specific VPC

                    "VpcId": "vpc-12345XYZ"

When running awless list instances - there are only certain attributes (properties) available
ID, Zone, Name, State, Type, Public IP, Private IP, Uptime, keypair.

I cannot find a way to modify the list to include a VpcId
And also I am not able to filter on a VpcId

Is this possible?

**Comment by fxaguessy** [comment]
For now, it is not possible to change the properties displayed in tables. But this is something we want to add (cf issue #87).
As a result, you can only get an instance's Vpc using `awless show instance-name/instance-id` but can not filter on this VPC (until #87 is fixed).
