### ISSUE TITLE
Feature request: Route tables showing subnet associations

### ISSUE THREAD

**Issue by stevenringo** [wallix/awless#123]
`aws ec2 describe-route-tables` shows an array of _associations._ It would be great if `awless list routetables` would do the same. `awless show rtb-xxxxxxxx` also does not show the associations.

Would love to have this information, or perhaps I am looking in the wrong place? Thanks so much.

**Comment by fxaguessy** [comment]
Thanks for the suggestion, this is a good idea. This will also make more easy the usage `awless detach routetable association=...`.
