### ISSUE TITLE
Reverse sort and adding tags to output?

### ISSUE THREAD

**Issue by deinspanjer** [wallix/awless#126]
Trying to get a handle on an explosion of snapshots.  Would be useful to do a reverse sort on the Created column (for now, resorting [snicker] to running in csv output and then doing a `| tac`.

Also, any way to get the tags into the output?

**Comment by simcap** [comment]
Indeed a reverse sort flag will come in handy, so we will add it.

For the tags of a `snapshot`, we do [sync them](https://github.com/wallix/awless/blob/master/aws/conv/model.go#L100) when fetching a snapshot. We do not display them as part of the listings, as we have not find a way to do so while keeping a readable listing output.

Although less scriptable, the snapshot's tags will be shown with the `awless show` output if I am not mistaken. For example: `awless show snap-071573255d4a764ce`.

Note: when running multiples times a listing to craft my output, I find very useful the global flag `--local` to avoid re-fetching everything each time. (_Of course at least a sync or cmd triggering a sync should have been done_). I even have an alias `alias awl=awless --local`.

**Comment by simcap** [comment]
You might know as well that you can filter by tags. Doing a `awless ls -h`:

```
...
--tag stringSlice         Filter EC2 resources given tags (case sensitive!). Ex: --tag Env=Production
--tag-key stringSlice     Filter EC2 resources given a tag key only (case sensitive!). Ex: --tag-key Env
--tag-value stringSlice   Filter EC2 resources given a tag value only (case sensitive!). Ex: --tag-value Staging
...
```

Also `tags` are so central to good AWS management that we will add other features around them. @deinspanjer If you have ideas let us know.

**Comment by deinspanjer** [comment]
Thanks, this is very helpful.  One more that I hope is related enough to tag along as a comment.

I ran `list instances`, `list volumes`, `list snapshots` and copied each of those outputs into an Excel workbook.  I then used COUNTIF and SUMIF to count up the number of snapshots per volume and the number of volumes per instance.  This gives me a pretty good accounting for the bad actors and low hanging fruit.

I grabbed one of the volume ids and I wanted to get just the snapshots for that volume so I tried running a command that gave an error.
```
➜  aws git:(master) ✗ awless list snapshots --ids --filter Volume=vol-91f5176b
[error]   Invalid filter key 'Volume'. Expecting any of: ID, Name. (Note: filter keys/values are case insensitive)
```

Is it intended that if you use --ids, you can only filter on the ID or the Name?

**Comment by deinspanjer** [comment]
That is a good point about the inspector.  Let me take a look at the bucket sizer one and see what I can do.  I'll open a new issue if I get stuck or have something to offer.

**Comment by simcap** [comment]
When you say `I wanted to get just the snapshots for that volume`, since the `volume` in our model is the parent of a `snapshot`, if you `awless show` a volume you should see in the `# Relations` section the snapshots children - if they are any (otherwise it is a bug). Ex:

```
awless show --local vol-00f2d4cea0738f55e
```

But as you see the output of the `show` command is not yet really scriptable or grepable.

**Comment by deinspanjer** [comment]
Yes, I do see the snaps listed for a volume.  What I was missing was that the `show instance` doesn't list the volumes attached to it.  The only mention of them is in the `Depending on:` section where it shows their aliases -- `@instance.name[volume], @instance.name[volume]`
