### ISSUE TITLE
Follow XDG spec for config and data

### ISSUE THREAD

**Issue by edubxb** [wallix/awless#128]
Currently awless stores its configuration and data in:

`~/.awless/`

Would be nice if the files location will be splitted as follows:

config → `~/.config/awless`
data → `~/.local/share/awless` or `~/.cache/awless` (depending of the kind of data stored)

+info: https://specifications.freedesktop.org/basedir-spec/latest/

**Comment by simcap** [comment]
Good suggestion. 

So far `awless` chose simplicity and went with the conventional `~/.myprogram/` directory to store its config, data and others. Its accounts well for Windows (where `awless` is really needed). Also we are still improving on our config files and format, what we cache, etc.... Up until now it avoided scattering `awless` resources on user's machines and was convenient in our development cycle. I understand switching to XDG spec would not much encumber all of that.

Anyway that is something that we shall consider when going out of beta. Thanks!
