### ISSUE TITLE
Option to force colored output

### ISSUE THREAD

**Issue by edubxb** [wallix/awless#129]
When using `awless` as input for another command, e.g. using pipes, the output isn't colored.

Would be nice to have an option to force colored output regardless if will be printed in a terminal or used as input for another command.

`git` allows this with the option `--color=always`.

**Comment by simcap** [comment]
That could be useful indeed so as to keep clarity of output even when piping. Not sure how to do that though yet.

**Comment by edubxb** [comment]
Just tested it, works like a charm! Thanks!
