### ISSUE TITLE
Exit with a status code greather than 0 when the `--local` flag is used but no data is found

### ISSUE THREAD

**Issue by edubxb** [wallix/awless#130]
Would be nice if `awless` will return an exit code greater than 0 when the `--local` flag is used but no data is found, p.e.:

`awsless show --local <instance id>`

so will be easy to check if the command returns no data when is used in scripts.

Currently the only way is redirecting the stderr to `/dev/null` and then check if there's no output in stdout.

IMHO checking status code is more elegant.

**Comment by simcap** [comment]
Consistent code status is paramount! Thanks for spotting this one. We will fix that.

**Comment by edubxb** [comment]
Works, thanks!
