### ISSUE TITLE
Allow using private ip for ssh

### ISSUE THREAD

**Issue by luisdavim** [wallix/awless#151]
for example, this command works:
```
awless ssh centos@i-0ab502440010ce2ed --through=dev-bastion
```
but if I try:
```
awless ssh centos@10.0.0.1 --through=dev-bastion
```
I get:
```
[error]   instance '10.0.0.1' not found
```
though `10.0.0.1` is the private ip for `i-0ab502440010ce2ed` and that is what it will be used for the connection anyway.

**Comment by simcap** [comment]
@luisdavim Thanks for spotting it. Fixing that.

**Comment by simcap** [comment]
Available in master as for now (`go get -u ....`)

**Comment by luisdavim** [comment]
Awesome. Thanks.

**Comment by varunchandak** [comment]
One more thing I would like to add that if the instance has private IP only, then `--private` parameter should not be required, and it should resolve that automatically. Correct me if I am wrong ?

**Comment by fxaguessy** [comment]
That would be indeed a nice improvement. I reopen this issue to track the implementation of this enhancement.

**Comment by varunchandak** [comment]
@fxaguessy can we get this too: 
![image](https://user-images.githubusercontent.com/18713091/41714092-d752efa6-756c-11e8-9dab-32d74564bf0d.png)
