### ISSUE TITLE
run awless on an EC2 node with an IAM role directly 

### ISSUE THREAD

**Issue by sandeepkunkunuru** [wallix/awless#163]
Can awless be run on an ec2 node with an IAM role directly? i.e. without having to use access keys or .aws/credentials

**Comment by fxaguessy** [comment]
Yes, you can run `awless` on an instance on which you gave an IAM role, without any configuration.

If you want to provision such an instance with awless, have a look for example to [this template](https://github.com/wallix/awless-templates#create-an-instance-with-preinstalled-awless-with-completion) which creates a role with ReadOnly permissions and create an instance with pre-installed `awless`.

**Comment by sandeepkunkunuru** [comment]
Thanks this is very helpful.
