### ISSUE TITLE
Problem with Homebrew and .zshrc

### ISSUE THREAD

**Issue by Bjorn121** [wallix/awless#164]
I'm not sure if this is the place to post this, but I'll give it a shot anyway.  If this is not the most suitable location, feel free to close it and remove it.

Every time you upgrade a package with Homebrew, the following line is added to ~/.zshrc

source <(awless completion zsh)

My iTerm was extremely slow and after some digging I opened ~/.zshrc to see if there was something strange in there.

It turns out that that source line was repeated about 50-60 times.  Every time you run brew upgrade, that line is added a couple of times, causing things to slow down.

I know this is probably more related to Homebrew, but perhaps someone here can give some advice on how to solve this.

**Comment by fxaguessy** [comment]
Thanks for reporting.
That was then a documentation issue. We fixed that in the [wiki](https://github.com/wallix/awless/wiki/Autocompletion-bash-&-zsh).
