### ISSUE TITLE
Adding rds stop/start ability

### ISSUE THREAD

**Issue by varunchandak** [wallix/awless#169]
As per AWS, we can stop/start RDS, which we do not have in `awless`. Will we get this update in next release ?

AWS CLI:
```
aws rds stop-db-instance --db-instance-identifier XYZ
```

**Comment by fxaguessy** [comment]
Hi,
Thanks for the suggestion, this is indeed a missing function in `awless`. 
We will try to add it in the next release.

**Comment by varunchandak** [comment]
Just FYI
* You can't stop a DB instance that has a Read Replica, or that is a Read Replica.
* You can't stop a DB instance that is in a Multi-AZ deployment.
* You can't stop a DB instance that uses Microsoft SQL Server Mirroring.

as per this [link](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_StopInstance.html#USER_StopInstance.Limitations)
