### ISSUE TITLE
LoadBalancers Not Found

### ISSUE THREAD

**Issue by varunchandak** [wallix/awless#180]
Trying this command:
```
vrnchndk: varun$ awless -p XXXXX -r ap-southeast-1 list loadbalancers
No results found.
```

Any specific settings do I need to change or is this something missing in the current version (0.1.8) of awless ? I have around 5-6 ELB in `Singapore` region and 10-15 in `Mumbai` region.

**Comment by simcap** [comment]
It is certainly due to the fact that the load balancers you are trying to list are legacy AWS load balancers. `awless` so far supports the new load balancers (API elbv2) only.

**Comment by varunchandak** [comment]
So I can safely assume that the legacy ELB won't be supported in the future releases ?

**Comment by simcap** [comment]
Yes, unfortunately do not count on it :( With our current roadmap we prefer to focus on upcoming and very important feature. 

(Unless one of us will find some time before the summer to have a look at it.)
