### ISSUE TITLE
ALIAS records not visible in Route53 output

### ISSUE THREAD

**Issue by varunchandak** [wallix/awless#181]
Trying this command:
```
awless -p XXXX -r ap-southeast-1 list records --filter name=xxx --columns type,name,records
```
I do get the output, but the **ALIAS** records do not display in the route53 output.

| TYPE   |                         NAME                         |                        RECORDS                        |
|--------|------------------------------------------------------|-------------------------------------------------------|
| A      | devapi.xxx.in.                                      | 11.22.33.44                                          |
| A      | beta.xxx.in.                                        |                                                       |
| A      | xxx.in.                                             |                                                       |
| A      | dev.xxx.in.                                         | 11.22.33.44                                          |
| A      | api.xxx.in.                                         | 11.22.33.44                                         |
| A      | www.xxx.in.                                         |                                                       |

Is this a bug or a missing feature ?

**Comment by simcap** [comment]
Well spotted! Thanks @varunchandak  

Missing in the implementation. I am correcting that now. Should be part of the 0.1.9 that will be released probably tomorrow.

(We will create a new column ALIAS though ... no real choice with the way the current AWS API is done)

**Comment by fxaguessy** [comment]
This is in [0.1.9](https://github.com/wallix/awless/releases/tag/v0.1.9) which has been released.
