### ISSUE TITLE
unable to filter scalinggroups using tags

### ISSUE THREAD

**Issue by varunchandak** [wallix/awless#183]
I am trying to get output of hundreds of ASGs in my infra, but I am unable to filter them using tags.

Command:
`awless list scalinggroups -p PROFILE --tag Environment=loadtesting`

No results !

**Comment by fxaguessy** [comment]
Hello,

Until now we did not fetch the tags of autoscaling groups in our local model (for example you will not see them in `awless show` command), thus we can not filter on tags.
However, this should be easy to add (c.f. [here](https://docs.aws.amazon.com/sdk-for-go/api/service/autoscaling/#Group)). We are currently on an important design improvement of the AST used to compile templates, but afterward we will add this to the model.

**Comment by simcap** [comment]
@varunchandak Available in latest (stable and compatible) master for validation.

Tags are now part of the model on auto scaling groups. You can see them all for a specific scalinggroup by doing:

```sh
awless show my-scaling-group-name -l
```

You can filter using tags with the usual tag flags available in listing:

```sh
awless ls scalinggroups --tag-key Env
awless ls scalinggroups --tag-value loadtesting
awless ls scalinggroups --tag Env=Production
```

**Note that filtering via tags is case sensitive and has to be an exact match** (there is an issue to improve on that and have wildcards).

Let me know if that works well for you and I will close this issue. Thanks!

**Comment by simcap** [comment]
I will close this issue then. Re-open if needed

**Comment by varunchandak** [comment]
just tested this and it's working as intended. Thanks !
