### ISSUE TITLE
Ability to filter by Tag

### ISSUE THREAD

**Issue by moulip** [wallix/awless#185]
Hi team,

What should be great is the ability to filter instances by tag.
i.e. : ls instances --filter tag=...

**Comment by simcap** [comment]
@moulip This exists already. You can get the details through the help `awless list -h` (or `awless ls -h`)

Here are 3 examples showing how to filter only on tag keys, tag values or both at the same time:

`awless ls instances --tag-key env`
`awless ls instances --tag-value=training` 
`awless ls instances --tag env=Training`

(note the equal sign is not mandatory)

Also `--filter` are only to filter on resources properties (i.e. values viewed in the output)
