### ISSUE TITLE
add core as one of candidate username for ssh

### ISSUE THREAD

**Issue by rohit-zabbed** [wallix/awless#202]
Can you please add core as in coreos default user for ssh.

**Comment by simcap** [comment]
Indeed. 

It has been some time that I wanted to add also CoreOS when creating an instance. I am looking into that as well.

**Comment by simcap** [comment]
@rohit-zabbed In the meantime you can try now on the latest master. You should be able to ssh to your coreos instances.

(Will be included in the next 0.1.10 otherwise)

**Comment by simcap** [comment]
Added CoreOS latest stable only distro support. Meaning you can create latest CoreOS stable instance easily with:

```sh
$ awless create instance name=testing-coreos
Please specify (Tab for completion, Enter to skip optionals, Ctrl+C to quit):
The distro query to resolve official community free bare distro AMI from current region. See `awless search images -h`:
instance.distro? coreos:coreos 
...
```

Then ssh to it with just using its name

```sh
$ awless ssh testing-coreos
```

When doen you can remove everything with a revert:

```sh
$ awless revert $(awless log -n1 --id-only)
```

@rohit-zabbed If it is all good for you let me know I and will close this issue. Thanks!

**Comment by rohit-zabbed** [comment]
@simcap Looks good, everything works as expected. Thanks
