### ISSUE TITLE
Unable to use mfa when role_arn is not set.

### ISSUE THREAD

**Issue by madelaney** [wallix/awless#207]
I'm trying to use awless (version 0.1.10), with AWS using MFA, awless doesn't ask for the MFA token.

When I try to create the bucket here is the output (including `-v` and `-e` flags):
__awless -v -e create bucket name=testingbucket__
```
[verbose] awless v0.1.10 - loading AWS session with profile 'default' and region 'us-east-1'
[verbose] Dry running template ...
create bucket name=testingbucket

Confirm (region: us-east-1)? [y/N] y
[extra]   resolved template author: user/madelaney
[extra]   s3.CreateBucket call took 1.246356208s
[info]    KO create bucket
          AccessDenied: Access Denied
````

__$HOME/.aws/config__
```
[default]
source_profile = XXXXXX-madelaney
mfa_serial = arn:aws:iam::XXXXXXXXXX:mfa/mdelaney
```
__$HOME/.aws/credentials__
```
[XXXXXX-madelaney]
aws_access_key_id = XXXXX~~~~~XXXXXXX
aws_secret_access_key = XXXXX~~~~~XXXXXXX
```

**Comment by fxaguessy** [comment]
Hi @madelaney,
Thanks for reporting. This might be related to #196 and 5c172163634e42e7bce4a993e17ee0562f0409f6.
Do you know if it worked previously with awless `v0.1.9` ?

**Comment by madelaney** [comment]
@fxaguessy , I just tried using [darwin-v0.1.9](https://github.com/wallix/awless/releases/download/v0.1.9/awless-darwin-amd64.tar.gz) and it's still happening.

__./awless -v -e create bucket name=hello-there__
```
[verbose] awless v0.1.9 - loading AWS session with profile 'default' and region 'us-east-1'
[verbose] Dry running template ...
create bucket name=hello-there

Confirm? [y/N] y
[extra]   resolved template author: user/madelaney
[extra]   s3.CreateBucket call took 183.16091ms
[info]    KO create bucket
          AccessDenied: Access Denied
```

(both $HOME/.aws/{config,credentials} were not changed between testing versions)

**Comment by madelaney** [comment]
Are there docs on how to setup the development environment? I'll see if I can get more information on my side.

**Comment by fxaguessy** [comment]
Hello,
Sorry, I read too fast the title of the issue. The problem is indeed that there is no role_arn in your config. AFAIK, using MFA without assuming a role was not possible in aws-sdk-go (cf [this issue](https://github.com/aws/aws-sdk-go/issues/1370)). As a result, for now, the only way to use MFA is assuming a role:

```
[XXXXXX-madelaney]
aws_access_key_id = XXXXX~~~~~XXXXXXX
aws_secret_access_key = XXXXX~~~~~XXXXXXX
```
and

```
[default]
source_profile = XXXXXX-madelaney
mfa_serial = arn:aws:iam::XXXXXXXXXX:mfa/mdelaney
role_arn = arn:aws:iam::XXXXXX:role/mfa-user
```

**Comment by madelaney** [comment]
Blurg. Thanks for the link, I'll watch that issue and see what happens.
