### ISSUE TITLE
Can't install awless on Linux because can't look up "updates.awless.io" hostname

### ISSUE THREAD

**Issue by atsaloli** [wallix/awless#293]
Is something happening with the DNS for updates.awless.io?  I can't look up the hostname, the DNS server is refusing connection:

```
$ host updates.awless.io NS-20.AWSDNS-02.COM
Using domain server:
Name: NS-20.AWSDNS-02.COM
Address: 2600:9000:5300:1400::1#53
Aliases: 

Host updates.awless.io not found: 5(REFUSED)
[:~] 1 $ 

```

**Comment by atsaloli** [comment]
I installed `awless` by downloading the latest version from https://github.com/wallix/awless/releases/tag/v0.1.11

**Comment by hbbio** [comment]
Just noticed that Wallix (who owns the domain) has probably shut down all servers, the website is gone too.

Really sad to see this, all of us who made awless left the company a few years ago.

Set `upgrade.checkfrequency` to 0 in the config file to disable the checks, I don't think there will be a new version unless the project is forked.

**Comment by atsaloli** [comment]
Understood, thanks @hbbio .  `awless` is a very nice tool.
