### ISSUE TITLE
Unsure how to use a profile

### ISSUE THREAD

**Issue by bdunbar** [wallix/awless#33]
Like many people, I manage a number of AWS accounts.  Is there a way to have awless use a profile, as the official AWS CLI does?

For example, given I have a typical setup, development in one account, production in another, with AWS CLI I have this.

# ~/.aws/credentials
[default]
aws_access_key_id = obfuscated
aws_secret_access_key = obfuscated

[DEV]
aws_access_key_id = obfuscated
aws_secret_access_key = obfuscated

[PROD]
aws_access_key_id = obfuscated
aws_secret_access_key = obfuscated

# aws s3 ls --profile DEV

I can easily work around exporting the keys to the appropriate env variables, so this isn't a *huge* deal but it would make things work way better.

Thanks!

~bdunbar

**Comment by fxaguessy** [comment]
Thanks for your feedback.
Indeed, for now we only take into account the `default` credentials of the ~/.aws/credentials file. But for sure, we will add very soon the support of other profiles, via `awless config`.

**Comment by carlf** [comment]
:+1: This is a big blocker for me. This project looks really promising but I can't use it without some annoying shim unless awless supports profiles.

**Comment by punnie** [comment]
Hm.. I'm able to list resources on different profiles by setting the `$AWS_PROFILE` environment variable to the desired one. Much like it works on AWS CLI.

```
export AWS_PROFILE=dev
awless list users
```

**Comment by fxaguessy** [comment]
Thanks @punnie , that's a nice workaround until we provide a easier way to select the profile to use in `awless`

**Comment by jefe78** [comment]
This is also a blocker for us to use this as we use many profiles.

**Comment by fxaguessy** [comment]
You can now change profile in `awless` using `awless config set aws.profile mynewprofile`. This is already in master and will be in 0.0.14.
