### ISSUE TITLE
Homebrew: No available formula with the name "awless"

### ISSUE THREAD

**Issue by StevenBlack** [wallix/awless#35]
After `brew update`, just to be sure, `brew install awless` returns `No available formula with the term "awless"`.

MacOS latest, homebrew latest...

Tried on two separate development Macs.

**Comment by joekr** [comment]
Did you make sure to `brew tap wallix/awless;`? The brew instructions worked for me.

But then again I'm still on OSX 10.11.6

**Comment by StevenBlack** [comment]
Works!  Thank you!

**Comment by StevenBlack** [comment]
Suggest you update [this wiki page](https://github.com/wallix/awless/wiki/Installation) with that `brew tap` step.

I would have done-so, but the wiki isn't open to community editing.

**Comment by simcap** [comment]
Thanks. I have updated the wiki. (Soon we will not need the `tap` anymore and will be officially in brew and simply install it with `brew install awless`)
