### ISSUE TITLE
Flag to disable statistics collection

### ISSUE THREAD

**Issue by hbbio** [wallix/awless#38]
We should have a flag that disables the collection of statistics, and explain this in the README.

**Comment by bitemyapp** [comment]
If stat collection is not opt-in, you're still going to get a lot of push-back. It should fail-safe, not fail-leak-data.

**Comment by ceejayoz** [comment]
Agreed with @bitemyapp. I'd personally be fine with an on-first-run "Is it OK if we..." prompt.

**Comment by bitemyapp** [comment]
>I'd personally be fine with an on-first-run "Is it OK if we..." prompt.

I wouldn't. Opt-in, period. Prompts in unix command line applications are obnoxious.

**Comment by yeukhon** [comment]
While the tool developer(s) can decide to enable this by default or not, or completely ignore it, my 2 cents = I don't see the reason to have this collected. Just ask people to fill out survey in the future, on upgrade.

**Comment by fxaguessy** [comment]
We are going to design a better way to collect stats. In the meantime, we have disable the data collection in f6389e75787390bd779773a5e253bdb7a5947ddc.

**Comment by Ghoughpteighbteau** [comment]
OK. I'm not as happy about this. Egg on my face, I did not notice the stats collection, had you asked. I would have immediately said no, had I noticed it was non-optional, I would not have installed, and I was overly trusting of an open source project and did not vet it carefully. Serious egg on my face here. 

I can be fairly sure you're on level, you have no ill intent, and you don't intend to de-anonymize anything... But had you asked me if I wanted to send you an overview of our general infrastructure, what we're doing with it, AMI's we're using at what level, to a random organization on the internet, the answer would have been *emphatically* no. 

I think more respect should have been paid, and I hope in the future, will be paid, to user information. I was not comfortable with the information that just leaked from the dimwitted actions I just took. 

I mean no disrespect, this tool looks great.

**Comment by bitemyapp** [comment]
@Ghoughpteighbteau from HN:

>The metrics include the instance id, account id, a list of the commands run with timestamps, the region, a bunch of metadata about the number of VPCs, Subnets, IAM users and policies, etc. Which is kind of a lot to get, and definitely isn't anonymous. Why do they need to know how many VPCs, Subnets, IAM users, and IAM roles I have?

**Comment by Ghoughpteighbteau** [comment]
I think I can add that they're collectiong EC2 instances, they're type, and the AMI's they're provisioned from. I'm not sure if this is an aggregate or a list. I was just skimming through stats: https://github.com/wallix/awless/blob/master/stats/stats.go

**Comment by Ghoughpteighbteau** [comment]
wait sec. am I reading this right?

https://github.com/wallix/awless/blob/master/stats/stats.go#L141

So this means it would wait 24 hours before sending that stats package?

**Comment by DanyC97** [comment]
@fxaguessy am a bit curious: what was the use case for collecting stats?
