### ISSUE TITLE
Anonymized values aren't anonymous

### ISSUE THREAD

**Issue by willglynn** [wallix/awless#39]
Over [on Hacker News](https://news.ycombinator.com/item?id=13662339), @fxaguessy wrote:

> The hash functions are totally unrevertable, so it is impossible to come back to the original identifiers.

I replied:

> You don't need to break SHA256 to de-anonymize these values.
>
> `awless` collects account number hashes. AWS account numbers are 12 decimal digits long, meaning there's a total of 10^12 unique values. Values are anonymized before submission using a single round of SHA256, so in ~2^40 hash operations, anyone with your database of hashes can invert every single account number.
>
> For comparison, the bitcoin blockchain presently has a hash rate of ~2^61 SHA256 hashes per second. (Edit: I incorrectly stated 2^41 based on a hash rate of 3 TH/s, when it's actually 3 *million* TH/s.)

"SHA256 with a global salt" is not appropriate for password storage because it is trivial to brute force. It is equally inappropriate for the anonymization of user identifiers, and for exactly the same reason.

However the statistics reporting works going forward (#38), `awless` should not continue using this or any other similar anonymization scheme.

**Comment by fxaguessy** [comment]
Hi, thanks for your feedback. We will design a better way to build and send truly anonymous data.
In the meantime, I just disabled the data sending (cf commit f6389e75787390bd779773a5e253bdb7a5947ddc).

**Comment by fxaguessy** [comment]
Fixed by f135c87fc6e48fb322a3f4953d6729b37754f5a7
