### ISSUE TITLE
Inconsistent/Missing Info on list buckets

### ISSUE THREAD

**Issue by jefe78** [wallix/awless#41]
Running 'awless list buckets' shows ~1-2 buckets out of a total of ~50 in our account. There doesn't seem to be a pattern to this.

**Comment by fxaguessy** [comment]
`awless list buckets` list the buckets that are in your current region (you can get it with `awless config get region` and change it with `awless config set region`).
So perhaps the other buckets are in another region ?

**Comment by jefe78** [comment]
We have 60 buckets in us-standard. This is the output of running the command several times. The output isn't even consistent.

+-------------------------+--------+---------------+
|         NAME ▲          | GRANTS |  CREATEDATE   |
+-------------------------+--------+---------------+
| ******-build-artifacts |        | 17 months ago |
+-------------------------+--------+---------------+
$awless list buckets
+-----------------------------------------+--------+--------------+
|                 NAME ▲                  | GRANTS |  CREATEDATE  |
+-----------------------------------------+--------+--------------+
| elasticbeanstalk-us-west-2-643667304694 |        | 3 months ago |
+-----------------------------------------+--------+--------------+
$awless config get region
us-east-1
 $awless list buckets
+-----------------+--------+-------------+
|     NAME ▲      | GRANTS | CREATEDATE  |
+-----------------+--------+-------------+
| ******-lambda-main |        | 4 weeks ago |
+-----------------+--------+-------------+
$awless list buckets
+-------------------------------+--------+---------------+
|            NAME ▲             | GRANTS |  CREATEDATE   |
+-------------------------------+--------+---------------+
| *****-****-archive-logs |        | 17 months ago |
+-------------------------------+--------+---------------+

**Comment by fxaguessy** [comment]
This is in fact related to #44. We identified the bug: when fetching buckets, the AWS API returns all buckets, even those which are not in the region, which confuse the fetching function. We are now working on a fix for #44 which should fix also this.

**Comment by fxaguessy** [comment]
This should be fixed since `awless 0.0.14`. Could you test with the latest version of awless ([0.0.15](https://github.com/wallix/awless/releases/tag/0.0.15)) that it works as expected ?
