### ISSUE TITLE
Support IAM instance profile credentials

### ISSUE THREAD

**Issue by copumpkin** [wallix/awless#42]
I'm trying to use `awless` from a machine that has valid (temporary) credentials on the standard 169.254.169.254 endpoint and it complains:

```
command hook failed: Your AWS credentials seem undefined!
AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY need to be exported in your CLI environment
```

My expectation from all other AWS tools and SDKs is that it would respect explicitly provided credentials if provided, but would fall back on the instance metadata credentials if those weren't provided.

**Comment by copumpkin** [comment]
A corollary to this would be to also optionally support a third environment variable for the session token provided by temporary credentials.

**Comment by jefe78** [comment]
This has already been requested and acknowledged in another issue.

**Comment by copumpkin** [comment]
@jefe78 why the thumbs-down?

**Comment by fxaguessy** [comment]
We intentionally disabled this way to log into AWS, as it was slowing significantly the CLI, when no credentials were provided. It was freezing several minutes (trying to connect to 169.254.*) before throwing an error.
If we find a workaround to add [this credential provider](https://github.com/wallix/awless/blob/master/vendor/github.com/aws/aws-sdk-go/aws/defaults/defaults.go#L100) without slowing the CLI, we will put it back.

**Comment by copumpkin** [comment]
Weird, the standard SDKs don't slow down at all; not sure what they do, but `aws-sdk-go` is one example in Go that I use all the time (in other tools) and I've never seen the freezing behavior.

**Comment by copumpkin** [comment]
It looks like they do [this](https://github.com/aws/aws-sdk-go/blob/master/aws/ec2metadata/service.go#L54-L57):

```go
		cfg.HTTPClient = &http.Client{
			// use a shorter timeout than default because the metadata
			// service is local if it is running, and to fail faster
			// if not running on an ec2 instance.
			Timeout: 5 * time.Second,
		}
```

**Comment by fxaguessy** [comment]
This should be fixed in [the last version](https://github.com/wallix/awless/releases/tag/0.0.15)  of `awless`. Could you please test if it is working as expected ?
