### ISSUE TITLE
Is it possible to describe a particular instance?

### ISSUE THREAD

**Issue by hossbert** [wallix/awless#46]
For example:
`awless list instances --id i-0413908eb542d8102`

to see all the attributes of that instance include its EC2 tags.

**Comment by fxaguessy** [comment]
This is the purpose of the `show` command. Run

    awless show i-0413908eb542d8102

This will display all the attributes of the instance. But, for now, we do not fetch the EC2 tags (except) the name.

**Comment by hossbert** [comment]
PKIERNAN-04:~$ awless show i-0413908eb542d8102
[info] cannot resolve resource - running full sync
Error: BucketRegionError: incorrect region, the bucket is not in
'us-west-2' region
status code: 301, request id:

**Comment by fxaguessy** [comment]
Now this is a duplicate of #44

**Comment by fxaguessy** [comment]
Fixed by 5bfa794. See [Changelog](https://github.com/wallix/awless/blob/master/CHANGELOG.md) for details.
