### ISSUE TITLE
Filter results

### ISSUE THREAD

**Issue by rektide** [wallix/awless#53]
Hi. When having a large number of resources, I find awless is for me hard to use. I'd like some ability to filter results. Typically I use tags to identify resources, and would want to filter for resources who have a tag that matches some kind of value.

**Comment by simcap** [comment]
Filtering in listing is definitely a feature we are going to add. We are thinking about the best way to go about it: custom flags, generic filter flag, etc ...

@rektide To get an idea though, in this case, what is a large number of resources (100, 1000, ...) and for what type of resources (instances, buckets)?

**Comment by rektide** [comment]
We have 700 ec2 instances in one region, that's the biggest count of anything we've got.

**Comment by simcap** [comment]
On master or upcoming in 0.0.15 (probably released today). See CHANGELOG and README for details on usage.
