### ISSUE TITLE
Inline change of configuration parameters 

### ISSUE THREAD

**Issue by fxaguessy** [wallix/awless#55]
As mentioned in #36, it would be nice to be able to change config parameters (for example, the region, or the aws profile) only for one command.

We could do that with, for example (git syntax)

    awless -c "aws.profile=prod" -c "region=us-west-2" list instances

**Comment by simcap** [comment]
Agreed on the flexibility it provides. 

Although I see another syntax for official/long term keys like aws-profile and aws-region. More like:

`awless list instances --aws-profile PROD`
`awless list instances --aws-region us-west-2`

It will be easier to type and clearer and more searchable in your command history (CTRL+r)

I'd rather keep the other git like syntax (` ... -c "" ...`)  for less official and maybe more dynamic config/properties

**Comment by fxaguessy** [comment]
Fixed by 8345814d0db328bc436aa4da208013fb79495f8a. Available in [0.0.17](https://github.com/wallix/awless/releases/tag/0.0.17).
