### ISSUE TITLE
"Error: empty field to add parent" during sync

### ISSUE THREAD

**Issue by thoellrich** [wallix/awless#56]
Just pulled the latest sources and rebuilt after issue #34 was marked as fixed. Now I see this:
```
$ awless version -e -v
awless version=0.0.13
$ awless sync -e -v
[info] running sync: fetching remote resources for local store
Error: empty field to add parent
```

Using dlv it appears we are here when it happens:
```
(dlv) bt
0  0x00000000004c113b in github.com/wallix/awless/cloud/aws.funcBuilder.addRelationWithField.func1
   at ./cloud/aws/parents.go:102
1  0x00000000004bf472 in github.com/wallix/awless/cloud/aws.(*Infra).FetchResources.func14
   at ./cloud/aws/gen_api.go:324
2  0x0000000000459331 in runtime.goexit
   at /usr/local/go/src/runtime/asm_amd64.s:2086
```

How can I find out what awless is complaining about?

**Comment by fxaguessy** [comment]
Thanks for the error investigation (and reporting).
This is due to a security group being in no VPC. We will add context to errors and fix this bug soon.

**Comment by fxaguessy** [comment]
You can now pull. This should be fixed.

**Comment by thoellrich** [comment]
:+1: - works fine now! Thanks!
