### ISSUE TITLE
Changing inbound source IP, for type, on security group

### ISSUE THREAD

**Issue by aadamsx** [wallix/awless#61]
My IP always change on the box I use to upload to my EC2 instance.  In these cases I go into my respective Security Group and change the Inbound source to my new IP and everything works nicely again.

It would be great if awless allowed for this.

So far I can get a list of my security groups like so:

$ awless list securitygroups

... and it displays the security group in question.  How do I get into that to change the inbound source on a particular type (ssh in my case) for a security group?

(super useful and awesome lib by the way)

**Comment by simcap** [comment]
@aadamsx In order to update the inbound source of a sgroup you can do:

`awless update securitygroup id=YOUR_ID inbound=authorize protocol=tcp cidr=0.0.0.0/0 portrange=22`

**This will work on the latest master**. If you use binary releases it will be available in the 0.0.15 (probably released today).

Let me know if that does solve your issues.

**Comment by aadamsx** [comment]
Thanks.

I do this:

> awless update securitygroup id=MY_ID inbound=authorize protocol=tcp portrange=22 cidr=MY_IP/32

and get the following error:

Error: expect either 'inbound' or 'outbound' parameter

**Comment by simcap** [comment]
Yes a bug surreptitiously crept into the 0.0.17!  So if you pull the master it will work (`go get -u github.com/wallix/awless`). I just tested it. 

Beginning of next week we will release the 0.0.18 with that fix and other features.

**Comment by fxaguessy** [comment]
Sorry, we introduced a bug in 0.0.17 that may cause this problem. This should be fixed on ˋmasterˋ. You can either test with the code on ˋmasterˋ, either waiting 0.0.18 that should be released next week.

**Comment by aadamsx** [comment]
I'm using brew for this, is it possible to change the version with brew?

**Comment by simcap** [comment]
No. Unfortunately, we will not be able to update the brew version until 0.0.18 is finalized.

After a `go get -u` you could make an alias `alias aw=$GOPATH/bin/awless` temporarily to work with the tip version

**Comment by fxaguessy** [comment]
You can now run `brew upgrade awless`, [0.0.18](https://github.com/wallix/awless/releases/tag/0.0.18) has been released.
Please let us know if it works as expected (or if it doesn't !)
