### ISSUE TITLE
40 columns on ssh

### ISSUE THREAD

**Issue by padilo** [wallix/awless#64]
When doing a ssh on an instance it sets the column size to 40. This makes tools that are based on column size very difficult to use it. For example `vi`.

**Comment by padilo** [comment]
@fxaguessy The commit added seems to just calculate this number when the connection is made, but it wouldn't take care if the user resizes his terminal session or just adds an splits or whatever it changes the width/height of the session.

The current solution is better than it was, but it stills has problems with width/height.
Should we reopen this issue or create a new one?

**Comment by fxaguessy** [comment]
In f00c43e5bc9a14def33b4c992946642f61d449bc we added that if a `ssh` client is present on the machine, `awless` uses this client to connect to the instance. Such a full ssh client (for example `openssh`) will support without problem terminal resize.
The `awless` builtin ssh client will stay just in case you don't have ssh installed (for example on Windows), and only as a simple temporary fix. It will not have as many feature as a full ssh client such as `openssh`.
