### ISSUE TITLE
Support for crossaccount profile access

### ISSUE THREAD

**Issue by linuxbsdfreak** [wallix/awless#66]
Hi,

I have multiple AWS accounts and i am connecting via a single account with a particular user and doing an assume role in another accounts.

For eg:

cat ~/.aws/config
[profile Account1]
source_profile = AccountMain
role_arn = arn:aws:iam::<accntNo>:role/CrossAccountAccessRole
region = eu-west-1

awless config set aws.profile  Account1 

It says 

command hook failed: Your AWS credentials seem undefined!
AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY need to be exported in your CLI environment

Is cross accounting supported?

Regards,
Kevin

**Comment by padilo** [comment]
Not sure about this, but as a workaroud you can set `AWS_PROFILE` environment variable.
```
export AWS_PROFILE=Account1
awless list instances
```

**Comment by fxaguessy** [comment]
You can now customize profile using:

1. `aws.profile` awless config key
2. `AWS_DEFAULT_PROFILE ` env variable
3. `--aws-profile` global flag.

See [README](https://github.com/wallix/awless#changing-aws-region-or-profile) for more details.

**Comment by linuxbsdfreak** [comment]
Tested and it works.

**Comment by soori1s** [comment]
Do I need to have IDs on each account to switch ? 

When connecting via a single account and doing an assume role in another accounts.Its asking me to provide Access and Security keys.

C:\Users\soori1s>awless list vpcs
Cannot resolve AWS credentials for profile 'Account1' (AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY)
Please enter access keys for profile 'Account1' (stored at C:\Users\soori1s\.aws\credentials):
