### ISSUE TITLE
show command with 17 character IDs isn't working

### ISSUE THREAD

**Issue by rbellamy** [wallix/awless#68]
Per the new [AWS ID length](https://aws.amazon.com/blogs/aws/theyre-here-longer-ec2-resource-ids-now-available/), I find `awless show i-wxyzaf21428e01234` throws the following error:
```
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument command: Invalid choice, valid choices are:
```

**Comment by rbellamy** [comment]
I should mention that with an ID of legacy length, everything behaves as expected:
```
awless show i-wxyz9dcd
[info] cannot resolve resource - running full sync
...
```

**Comment by simcap** [comment]
In your first comment, the console error seems to be from another `aws` tool than `awless`. I just want to make sure that you used/pasted/ran the show command with `awless`.

Also there is no real restriction on the param given to `awless show` so id sizes should not matter.

On my side I checked that on my latest. You can give me the version (`awless version`) or sha you are on and I will test it on my side.

**Comment by rbellamy** [comment]
Wow. Just wow. I'm an idiot. Sorry for the noise...

**Comment by simcap** [comment]
@rbellamy No worries. Keep testing :simple_smile:! Version 0.0.15 is out
