### ISSUE TITLE
Add support for Classic ELB

### ISSUE THREAD

**Issue by rbellamy** [wallix/awless#71]
Please add support for classic ELB (ELBv1).

One of the superior features of `awless` is that it provides a dependency graph of entities - and though the Application ELB (ELBv2) is the most recent offering by AWS, there are going to be a huge number of extant Classic ELB's running out there - and having a good idea of their dependencies will provide an excellent utility when trying to upgrade them.

Furthermore, even today most tools provision Classic ELBs when managing AWS for you - for instance, current Kubernetes tooling creates ELBv1 entities.

**Comment by javipolo** [comment]
I was struggling to see my classic load balancers and I finally arrived here

+1 to this feature, we use classic ELBs intensively and it's a pity not being able to use awless on them :(

**Comment by yuriipolishchuk-finsight** [comment]
Same here, ELBV1 load balancers surprisingly aren't supported
+1 to the feature

**Comment by simcap** [comment]
@rbellamy @javipolo @yuriipolishchuk-finsight It has been done into master. Feel free to test it

**Comment by simcap** [comment]
@rbellamy @javipolo @yuriipolishchuk-finsight Forgot to point to how to use it:

* use `awless ls classicloadbalancers`, `awless create classicloadbalancer -h`
* here is [a template with a full example](https://github.com/wallix/awless-templates/blob/master/classic_load_balancer.aws)

**Comment by yuriipolishchuk-finsight** [comment]
@simcap seems to be working, thank you!

**Comment by simcap** [comment]
And also forgot tom mention. To see all properties on your classic load balancer:

```
awless show my-loadb-name -l
```

**Comment by javipolo** [comment]
I just tried it and I'm super happy, thank you! :)
