### ISSUE TITLE
need single line output for CNAME records with awless list records 

### ISSUE THREAD

**Issue by lakamsani** [wallix/awless#79]
Hi,

For a CNAME record command like this `awless records | grep CNAME`,  it is printing ttl on a second line like this. That makes it hard to write scripts that parse the output. 

| awls-c6380b5c | CNAME | alias.domain.com.       | real-host.amazonaws.com   
                                                                                                                                                             | 60     |

If you could print them all one one line that would be great on your next update.

**Comment by fxaguessy** [comment]
You should not use the default display format (`table`) to parse outputs in scripts. Tables are human readable and they may introduce line-breaks if entries are too long.
Use rather the csv (`./awless list records --format csv`) or tsv (`./awless list records --format tsv`) format that will be much easier to parse.

That being said, there was a bug in `0.0.19` in which `./awless list records --format csv/tsv` also added new lines inside records (which broke CSV/TSV format). This is now [fixed on `master`](https://github.com/wallix/awless/blob/master/CHANGELOG.md) and will be in next release.

Thanks for the bug report.

**Comment by lakamsani** [comment]
sounds good. thanks for making this handy tool available as open source.
