### ISSUE TITLE
Possibility to create AMI from a local image

### ISSUE THREAD

**Issue by moulip** [wallix/awless#84]
It would be cool to have the possibility to create an AMI from a locally created VM. 

For instance with aws shell, after having uploaded the OVA on S3
aws ec2 import-image --description "WAB_504" --disk-containers file:///myfile.json

**Comment by fxaguessy** [comment]
This can now be done with [this awless template](https://github.com/wallix/awless-templates#upload-image-from-local-file). Run it with the latest version of `awless` on `master` :

    awless run repo:upload_image -v

You have to specify the bucket in which the image will be copied, a description, and the VM filepath.

After running the template, you can monitor the progress of the AMI building with `awless list importimagetasks`. When the task is over, don't forget to remove the object on s3 with `awless delete s3object`

**Comment by moulip** [comment]
Good to know ;-)
I'll give it a try and be back to you ASAP with my feedback !
Thx

**Comment by fxaguessy** [comment]
This is now in [v0.0.24](https://github.com/wallix/awless/releases/tag/v0.0.24).
