### ISSUE TITLE
add ability to customize default output columns

### ISSUE THREAD

**Issue by kylewest** [wallix/awless#87]
Is there a way to customize the default columns when running a command like:

```bash
awless ls instances --sort name
```

I see they are defined [here](https://github.com/wallix/awless/blob/master/console/defaults.go) and used [here](https://github.com/wallix/awless/blob/master/commands/list.go#L109) but don't see a way to change or append the default set. Ideally something like:

```bash
awless ls instances --sort name --show name,zone,state,subnet,imageId
```

or maybe:

```bash
awless ls instances --sort name --extraColumns subnet,imageId
```

Are there plans to add this feature? I'd be happy to hack on it but haven't written any Go before so would need a little push in the right direction to get started.

**Comment by fxaguessy** [comment]
This is something that we want to add. We are currently thinking of the best way to support it and will let you know when it will be implemented. (It should be soon, stay tuned !)

**Comment by simcap** [comment]
Note the flag is `--columns`
