### ISSUE TITLE
support STS credentials

### ISSUE THREAD

**Issue by automaticgiant** [wallix/awless#89]
not handled by 999c979
```
[dev]
aws_access_key_id = REDACTED
aws_secret_access_key = REDACTED
aws_session_token = REDACTED
aws_security_token = REDACTED
token_expiration = REDACTED
```
`awless --aws-profile [dev] whoami`
produces
```
Error: Your AWS credentials seem undefined! AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY need to be exported in your CLI environment
Installation documentation is at https://github.com/wallix/awless/wiki/Installation
```

**Comment by fxaguessy** [comment]
Could you try rather with `awless --aws-profile dev whoami -v` (`-v` verbose flag will display the profile that is used to connect to AWS). There should not be `[` and `]` around the profile name.
But anyway, thanks for reporting, we will improve documentation.

**Comment by fxaguessy** [comment]
By the way @automaticgiant , as far as I know, in the `~/.aws/config` file, a new profile name should be prefixed with `profile`, i.e. :

```
[profile dev]
aws_access_key_id = REDACTED
aws_secret_access_key = REDACTED
aws_session_token = REDACTED
aws_security_token = REDACTED
token_expiration = REDACTED
```

**Comment by fxaguessy** [comment]
@automaticgiant is this issue still valid ? did you try again with the correct ~/.aws/config file ?

**Comment by sdouche** [comment]
Hi,
I use a working STS account:
```
$ eval (assume-role XXX)
$ aws ec2 describe-instances
{
    "Reservations": [
        {
            "ReservationId": "r-XXX",
...
```

But awless can't read something on the `whoami` command:

```
$ awless --aws-profile=sr-sandbox whoami
Username: , Id: XXX, Account: XXX
[error]   InvalidParameter: 1 validation error(s) found.
```

**Comment by automaticgiant** [comment]
oh yeah i guess you're right. i was doing it wrong.
now i see what @sdouche sees.

**Comment by sdouche** [comment]
No more error messages on 0.0.24:

```awless -p XXX whoami                                                                                           639ms
ResourceType: assumed-role, Resource: AdministratorAccess/XXX, Id: XXX, Account: XXX
```
