### ISSUE TITLE
selection behaviour by multiple tags should perform intersection

### ISSUE THREAD

**Issue by russ-te2** [wallix/awless#97]
Firstly, thank you for the very quick feature addition supporting tags!

I was wondering if query selection by multiple tags (as given in the examples) should perform intersection not union.  It was my expectation that `awless list instances --tag Env=prod,Customer=blue` for example would return all prod instances associated with the Customer 'blue'.

**Comment by simcap** [comment]
Thanks. Indeed intersection is better in this case and follows other CLIs behaviour.

Fixed in `master` branch (it did not make into this morning release 0.0.24). @russ-te2 if you having trouble installing or working from `master` let me know. 

Closing now.
