### ISSUE TITLE
awless stop instance ID returns an error message

### ISSUE THREAD

**Issue by sdouche** [wallix/awless#99]
Hi,
It common to write the instance ID in the CLI, but awless returns a error message:
```awless stop instance XXX
Error: error parsing template at line 1 (char 15):
	-> stop instance X
```
It would be cool to use the ID for starting / stopping / whatever the instance.

**Comment by fxaguessy** [comment]
This is *normal*, as you should write `awless stop instance id=i-1234` to stop an instance.

However, typing `awless stop instance i-1234` or even `awless stop i-1234` is a very common mistake and we are going to think if it's better to keep as it is, in order to educate to the template format (that requires, param=value). Or if we also add these shortcuts.

**Comment by simcap** [comment]
In the meantime (while we think of a good approach for that - several come to mind), here is something that can help.

Having the following bash functions in one's env  (`~/.bashrc`, `~/.zshrc` or distro appropriate).

```sh
function startinstance() {
 awless start instance id="$1" -f
}
function stopinstance() {
 awless stop instance id="$1" -f
}
function delinstance() {
 awless delete instance id="$1"
}
```
... and completion comes for free! The `-f` will avoid the prompt, as for stopping/starting one might not want to confirm.

So a typical use would be:

```sh
$ stopinstance @my-instance-name    # referring instance by name using the alias notation

or 

$ startinstance id-2352p52j452
```

**Comment by sdouche** [comment]
> This is normal, as you should write awless stop instance id=i-1234 to stop an instance.

Oh, my bad.

> However, typing awless stop instance i-1234 or even awless stop i-1234 is a very common mistake and we are going to think if it's better to keep as it is, in order to educate to the template format (that requires, param=value).

I'm ok with that, so maybe add a more valuable error message like:

```
Error: error parsing template at line 1 (char 15):
	-> stop instance X
See 'awless stop instance -h'
Did you mean this? awless stop instance id=ID
```

An integrated template manual will be helpful.

**Comment by sdouche** [comment]
Ok I know why I typed the wrong command:
`awless ssh ID` vs  `awless stop instances id=ID`

**Comment by fxaguessy** [comment]
> Ok I know why I typed the wrong command: awless ssh ID vs awless stop instances id=ID

Good point. Thanks for your feedback, we are going to search a better approach for this and at least improve error messages.

**Comment by hbbio** [comment]
Yes, that's my favorite awless typo too!

Building on what you suggest, we can catch both `awless stop instance (id)` and even `awless stop (id)` where `typeof(id)==instance_type` and:

1. Display the right suggestion: `Did you mean awless stop instance id=(id) (y/n)?`
2. Automatically accept 'y' as an answer to perform the action right away without having to copy/paste or type the command again
